### PR TITLE
Fixed test for new rooster teeth site

### PR DESCRIPTION
**Pull request by AevumDecessus**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Fixed the broken test to move forward with getting this merged into upstream

### CODE REVIEW

**Comment by AevumDecessus** [comment]
@ddmgy I have a current FIRST subscription with rooster teeth, and am willing to take over moving this forward if you would like. Your code works perfectly minus the one broken test so far.

**Comment by ddmgy** [comment]
That sounds fine. Is there a way to give control of the pull request to you? I'm not familiar with Github's controls.

**Comment by AevumDecessus** [comment]
If you merge this PR, it should update the original PR as well since it's the same branch, and then it should pass tests, you can just add a comment to the PR if they ask for more

**Comment by ddmgy** [comment]
Okay. I'll try to keep on top of any comments on the open pull request (and any new commits you might make) to get this merged as soon as it can.

**Pull request merged**
